In [2]:
#Training Pemrograman R - Sesi 4: Collection
x <- c(1:3)
c(3:5) -> y
#b <- array(1:3,array(1:3))
#b <- array(1:3,c(2,3,4))
c <- x + y
#    OR
     x - y -> c
#collide as one
#     ----->
#x = [1,2,3] |
#y = [3,4,5] |
#c = [4,6,8] v

a <- array(1:5)
# a[0] for header
# a[1] |output|>> 1


#ingat, yang akan dipenuhi dulu adalah kolomnya!!
#buktikan dengan array2 dimensi dibawah!!
b <- array(1:3,c(1,4)); message(print(b)) #1row x 4column
#|output|>> 1 2 3 1
b <- array(1:3,c(2,4)); message(print(b)) #2row x 4column
#|output|>> 1 3 2 1
#        >> 2 1 3 2
b <- array(1:3,c(3,4)); message(print(b)) #3row x 4column
#|output|>> 1 1 1 1
#        >> 2 2 2 2
#        >> 3 3 3 3


# coba array 3 dimensi
# array(nilai,besaran dimensi)
# array(data = ,dim = ,dimnames = )
# dimensi= c(x,y,z)
data.frame(head1 = c(1:3),head2 = c(1:3)) -> z

# dim4      dim3    dim2
# (1,1)
#    aaa
#    axx
# (1,2)     (1)
#    aaa     aaa
#    bxx     bbb    (NA)
#                     aaa
# (2,1)     (2)       bbb
#    bbb     aaa
#    axx     bbb
# (2,2)
#    bbb
#    bxx
#message(print(b)) #Error in array(1:3, 1, 2): 'dimnames' must be a list
metriku.size.r=3
metriku.size.c=4
metriku.size.m=3

metriku.names.matrix <- paste("metrik",seq(1:metriku.size.m),sep="_")
metriku.names.cols <- paste("kol",seq(1:metriku.size.c),sep=".")
metriku.names.rows <- paste(seq(1:metriku.size.r),"row",sep=".")


b <- array(1:3,c(metriku.size.r,metriku.size.c,metriku.size.m),dimnames = list(metriku.names.rows,metriku.names.cols,metriku.names.matrix))

print(b)
# Orange

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    1


1231


     [,1] [,2] [,3] [,4]
[1,]    1    3    2    1
[2,]    2    1    3    2


12312312


     [,1] [,2] [,3] [,4]
[1,]    1    1    1    1
[2,]    2    2    2    2
[3,]    3    3    3    3


123123123123


, , metrik_1

      kol.1 kol.2 kol.3 kol.4
1.row     1     1     1     1
2.row     2     2     2     2
3.row     3     3     3     3

, , metrik_2

      kol.1 kol.2 kol.3 kol.4
1.row     1     1     1     1
2.row     2     2     2     2
3.row     3     3     3     3

, , metrik_3

      kol.1 kol.2 kol.3 kol.4
1.row     1     1     1     1
2.row     2     2     2     2
3.row     3     3     3     3



In [4]:
library(tidyverse)
#practice sendiri
#https://it.unt.edu/sites/default/files/paste_jds_jun2013.pdf
#cheatsheet tai anyim kalo ga pernah dipake buat apa...

n <- 6
prefix <- paste0("prefix",seq(1:n))
suffix <- sprintf("sufix%d",seq(1:n))

my.names <- paste(prefix,suffix,sep = "@")
# my.names

#IDK
urut <- (as.list(c(paste0("coba",1:3)), all.names = TRUE))

#may need implement of my.names on any of column on dataset
#here with table column that name is .data
# names(my.data) <- my.names
#contoh matrix
# matrix(c(1,2,3,4, 11,13,13,5),2,4)

tabelku.rows <- 2
tabelku.cols <- 4
tabelku.totdim <- tabelku.cols * tabelku.rows

suffix <- sprintf("ok%d",seq(1:tabelku.totdim))

tabelku.matrix <- matrix(paste(prefix,suffix,sep = "_"),tabelku.cols,tabelku.rows)

new.matrix.1 <- matrix(rep(NA, tabelku.totdim), tabelku.cols)
#jika rows sudah dideclarasikan dan rows satu objek dengan cols
#maka cols tidak perlu ditulis kembali, berlaku sebaliknya
# misal
# matrik.ok1.cols
# matrik.ok1.rows
# new.matrix.1



practice_mdat_mbuh <- function(x,y,c){
    paste0("baris",seq(1:x)) %>% c() -> barisx
    paste0("kolom",seq(1:y)) %>% c() -> kolomx
    matrix(c(1:(x*y)),x   ,y      ,dimnames = list(barisx,kolomx),byrow = switch(c,"row"=T,"column"=F))
  # matrix(nilaitabel,nRow,nColumn,dimnames = list(anyX  ,anyY  ), byrow="T")
  # sebarkan nilai byrow/bycolumn [T/F]
}
#akan selalu mengisi kolomTerkecil, barisTerkecil
#hingga kolomTerkecil memenuhi barisTerbesar
#dilanjut kolomKedua dan memenuhi BarisTerbesar
#dst

#replicate
# each       = rep dimasing2 nilai
# c(x,y,z,o) = rep menyesuaikan iterasi nilai
# rep(nilai, each = 2, times = 2,length.out = 2)
# rep(1:4,c(1,1,1,1), length = 3)

# <- paste(
#             prefix,
#             paste(
#                 seq(1:tabelku.rows)[j],
#                 seq(1:tabelku.cols)[i]))
#fillup matrix
for(i in 1:tabelku.rows){
    for(j in 1:tabelku.cols){
        new.matrix.1 <- paste(
            prefix,
            paste(
                seq(1:tabelku.rows)[i],
                seq(1:tabelku.cols)[j],
                sep = "_"),
            sep = "."
        )
    }
    rm(i,j)
}
new.matrix.1

[1] "prefix1.2_4" "prefix2.2_4" "prefix3.2_4" "prefix4.2_4" "prefix5.2_4"
[6] "prefix6.2_4"